ARG ELK_VERSION

# https://www.docker.elastic.co/r/elasticsearch
FROM docker.elastic.co/elasticsearch/elasticsearch:${ELK_VERSION}

# Add your elasticsearch plugins setup here
# Example: RUN elasticsearch-plugin install analysis-icu
